### ISSUE TITLE
Error: result.map is not a function

### ISSUE THREAD

**Issue by ajsb85** [wk-j/github-detail-comment#10]
Hi @wk-j 

I saw this alert without the env vars:

![image](https://cloud.githubusercontent.com/assets/663460/22060336/9e29c348-dd70-11e6-9ad1-31c73b9ea0b9.png)

After add the env vars and try `>Create issue`, I can see this message in the devtools:

```console
[Extension Host] Congratulations, your extension "github-detial-comment" is now active!
[Extension Host] Error: spawn git ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Extension Host] Uncaught Exception:  TypeError: result.map is not a function
[Extension Host] TypeError: result.map is not a function
    at repo.getRemotes (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\out\src\github.js:14:35)
    at C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:688:18
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:728:18)
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:1188:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
result.map is not a function: TypeError: result.map is not a function
    at repo.getRemotes (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\out\src\github.js:14:35)
    at C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:688:18
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:728:18)
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:1188:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

Salut.

**Comment by wk-j** [comment]
This extension rely on [simple-git](https://github.com/steveukx/git-js) and it require **git** command.
Have you installed git on your system?

**Comment by ajsb85** [comment]
Hi @wk-j 

Git works in VS Code.

![image](https://cloud.githubusercontent.com/assets/663460/22143257/b76b2e48-def9-11e6-8ea9-8f24da455a95.png)

I have only the GitHub Desktop app and their shell.

In the PATH it's not ready.

![image](https://cloud.githubusercontent.com/assets/663460/22143361/1105e1e6-defa-11e6-810a-50da115456ee.png)

**Comment by wk-j** [comment]
I'm not sure how git work in your vscode without git in PATH
if you manual config git location with "git.path" please try github-detail-comment@0.0.9

**Comment by ajsb85** [comment]
Hi @wk-j 

Still the same error.

```console

[Extension Host] git (vscode.git) uses PROPOSED API which is subject to change and removal without notice
[Extension Host] Congratulations, your extension "github-detial-comment" is now active!
[Extension Host] Error: spawn git ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Extension Host] Uncaught Exception:  TypeError: result.map is not a function
[Extension Host] TypeError: result.map is not a function
    at repo.getRemotes (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\out\src\github.js:18:35)
    at C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\node_modules\simple-git\src\git.js:688:18
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\node_modules\simple-git\src\git.js:728:18)
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\node_modules\simple-git\src\git.js:1188:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
result.map is not a function: TypeError: result.map is not a function
    at repo.getRemotes (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\out\src\github.js:18:35)
    at C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\node_modules\simple-git\src\git.js:688:18
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\node_modules\simple-git\src\git.js:728:18)
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.9\node_modules\simple-git\src\git.js:1188:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

```

**Comment by wk-j** [comment]
I don't find a way to obtain git location.
I think you should configure Git Desktop to run from command line [Link](http://stackoverflow.com/questions/32261198/how-do-you-configure-github-desktop-to-run-from-the-command-line-in-osx)

**Comment by ajsb85** [comment]
Yes. Don't worry about the guy in PATH, I only want that you can handle the
error to a proper alert message and prevent the devtools error.

Salut.

**Comment by ajsb85** [comment]
Hi @wk-j so just use `vscode.workspace.getConfiguration("git").get("path", "git")` instead of "git"

**Comment by wk-j** [comment]
@ajsb85  Yes I'm using that trick but still not work in your case
https://github.com/wk-j/github-detail-comment/blob/master/src/github.ts#L16
