### ISSUE TITLE
Command 'extension.createIssue' not found

### ISSUE THREAD

**Issue by ajsb85** [wk-j/github-detail-comment#7]
Hi @wk-j

I can see this alert.

![image](https://cloud.githubusercontent.com/assets/663460/22060336/9e29c348-dd70-11e6-9ad1-31c73b9ea0b9.png)

![image](https://cloud.githubusercontent.com/assets/663460/22060321/8cd6d928-dd70-11e6-8a4f-82e065cc8092.png)

Error command 'extension.createIssue' not found

**Comment by ajsb85** [comment]
Hi @wk-j

I have this error message:

```console
[Extension Host] Activating extension `wk-j.github-detial-comment` failed: Cannot find module 'simple-git'.
[Extension Host] Activating extension `wk-j.github-detial-comment` failed:  Cannot find module 'simple-git'
[Extension Host] Here is the error stack:  Error: Cannot find module 'simple-git'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.i._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:19120)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.7\out\src\github.js:6:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.i._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:19120)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.7\out\src\extension.js:3:18)
    at Module._compile (module.js:556:32)
Activating extension `wk-j.github-detial-comment` failed: Cannot find module 'simple-git'.
command 'extension.createIssue' not found

```

- VSCode Version: Code - Insiders 1.9.0-insider (215a0af33046d3940e665d46ecaeac9623f2f769, 2017-01-19T07:12:16.209Z)
- OS Version: Windows_NT ia32 10.0.15007
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|ghlink|dt|0.0.5|
|EditorConfig|EditorConfig|0.3.4|
|Theme-Zenburn|gerane|0.0.3|
|sass-lint|glen-84|0.0.3|
|vscode-commitizen|KnisterPeter|0.3.5|
|vscode-github|KnisterPeter|0.9.0|
|debugger-for-chrome|msjsdiag|2.4.2|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-versionlens|pflannery|0.12.1|
|gitlink|qezhu|0.1.1|
|sass-indented|robinbentley|1.3.0|
|sharecode|RolandGreim|0.4.0|
|vscode-gtm|s3ramsay|0.1.2|
|github-detial-comment|wk-j|0.0.7|

---

Steps to Reproduce:

1. <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
2. Type: **Create issue** and <kbd>Enter</kbd>

**Comment by wk-j** [comment]
I just fixed
Please install github-detial-comment@0.0.8

**Comment by ajsb85** [comment]
Hi @wk-j 
Already updated 👍 

I saw this alert without the env vars:

![image](https://cloud.githubusercontent.com/assets/663460/22060336/9e29c348-dd70-11e6-9ad1-31c73b9ea0b9.png)

After add the env vars, I can see this message in the devtools:

```console
[Extension Host] Congratulations, your extension "github-detial-comment" is now active!
[Extension Host] Error: spawn git ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Extension Host] Uncaught Exception:  TypeError: result.map is not a function
[Extension Host] TypeError: result.map is not a function
    at repo.getRemotes (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\out\src\github.js:14:35)
    at C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:688:18
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:728:18)
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:1188:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
result.map is not a function: TypeError: result.map is not a function
    at repo.getRemotes (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\out\src\github.js:14:35)
    at C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:688:18
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:728:18)
    at Git.<anonymous> (C:\Users\username\.vscode-insiders\extensions\wk-j.github-detial-comment-0.0.8\node_modules\simple-git\src\git.js:1188:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

Salut.

**Comment by ajsb85** [comment]
Hi @wk-j 
Already updated 👍
